apiVersion: apps/v1
kind: Deployment
metadata:
  name: our-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: environs
  template: # template of the pod
    metadata:
      name: environment
      labels:
        app: environs
    spec:
      containers:
        - name: environment
          image: benadabankah/our-environment:v1
          ports: 
          - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: our-environment
spec:
  selector:
    app: enviro
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    